# Generated by Django 4.1.4 on 2023-12-04 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='answer_after_complete',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ после выполнения'),
        ),
    ]
